### ISSUE TITLE
Select secret other than password to copy

### ISSUE THREAD

**Issue by rnsc** [vinc3m1/1pa#1]
Hello,

First of all, thank you for your tool, it works well.
One thing that would be awesome to add, is the ability to select the field of the 1password item that we want to copy (in the case we want to copy an additional password field.

Thanks,

**Comment by vinc3m1** [comment]
Since adding a separate "chooser" is a bit complicated, instead I've added the ability to use a `-s` flag, which will show all password fields instead of masking them with ******* which should let you copy/paste whichever you like (just not automatically). While not ideal, this is the simplest solution for now.

**Comment by rnsc** [comment]
Hello @vinc3m1 , thank you for taking the time to do this, really appreciated!
